name: tavp-web-id
recipe: lamp
config:
  php: '8.3'
  webroot: public
  xdebug: false
  conf:
    php: .lando.php.ini
  env:
    PHP_TIMEZONE: "Asia/Jakarta"
    PHP_DEFAULT_TIMEZONE: "Asia/Jakarta"

services:
  database:
    type: mariadb:10.11
    portforward: 33306
    creds:
      user: tavp
      password: tavp
      database: tavp

  mailpit:
    type: lando
    services:
      image: axllent/mailpit
      command: /mailpit
      ports:
        - '8026:8025'

tooling:
  tavp:
    service: appserver
    cmd: php /app/vendor/bin/tavp
  phalcon:
    service: appserver
    cmd: /bin/bash /app/vendor/tavp/cli/scripts/install-phalcon.sh
    description: Install the Phalcon C-extension in the container
  migrate:
    service: appserver
    cmd: php /app/vendor/bin/tavp migrate
    description: Run database migrations
  seed:
    service: appserver
    cmd: php /app/vendor/bin/tavp seed
    description: Seed the database